import { Injectable } from '@angular/core';

import { Class } from '../models/class';

@Injectable({
  providedIn: 'root'
})
export class ClassService {
  allClasses: Class[] = [{classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'} ,{classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}, {classID: 'Clase 1', type : 'Tipo 1', instructorID : 'Yolanda Azofeifa Tablada', modality : 'Grupal', capacity : 3, date: ['K', 'J'], startTime :'7:30', endingTime : '15:30'}];

  constructor() { }
}
